---
version: "3.8"
services:
  movies:
    image: msuryaprakash06/movies
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: msuryaprakash06/train
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: msuryaprakash06/recharge
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: msuryaprakash06/dth
    ports:
      - 84:80
    deploy:
      replicas: 3
