---
version: "3.8"
services:
  movies:
    image: msuryaprakash06/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: msuryaprakash06/train:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: msuryaprakash06/recharge:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image:msuryaprakash06/dth:latest 
    ports:
      - 84:80
    deploy:
      replicas: 3
