---
version: "3.8"
services:
  movies:
    image:msuryaprakash06/surya  
    ports:
      - 61:80
    deploy:
      replicas: 3
  train:
    image:msuryaprakash06/prakash 
    ports:
      - 62:80
    deploy:
      replicas: 3
  recharge:
    image: msuryaprakash06/recharge
    ports:
      - 63:80
    deploy:
      replicas: 3
  dth:
    image:msuryaprakash06/dth 
    ports:
      - 64:80
    deploy:
      replicas: 3
